### ISSUE TITLE
error when exucuting

### ISSUE THREAD

**Issue by sonyusr** [ckuma/scplay#1]
"
Traceback (most recent call last):
  File "sc_main.py", line 16, in <module>
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
  File "sc_main.py", line 13, in main
  File "sc_playtime.py", line 43, in just_do_it
  File "sc_playtime.py", line 32, in get_totals
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 84558-84559: invalid continuation byte
"

**Comment by sonyusr** [comment]
neither release version works for me. the second doesnt give me an error, simply fails to run

**Comment by ckuma** [comment]
Hey @sonyusr, you might want to try the alternate version I've made.  
I basically remade the Python app using Windows WinForms and C# instead of Python.  
If that works for you let me know: https://github.com/ckuma/scplay/releases/tag/v3.1 
Cheers!

**Comment by ckuma** [comment]
@sonyusr
I'll keep this open for a little while in case you're still encountering an issue with the new version.  
If you're unavailable to test that out within the next few weeks I'll resolve the issue - in which case feel free to raise one for the C# version (3.1) if you're encountering version afterwards. Sorry for the delays!

**Comment by ckuma** [comment]
I'll close the issue since the C# version is _de facto_ default now, feel free to open an issue if necessary, thanks :)
